--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/matymare/AntiGenerationWorldScreen
build-by-default: true
branches:
- master
projects:
  AntiGenerationWorldScreen:
    path: ""
...
